name: Run Caddy

on:
  push:
    branches:
      - main  # Changez ceci pour la branche de votre choix

jobs:
  run-caddy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Caddy
        run: |
          curl -LO "https://github.com/caddyserver/caddy/releases/latest/download/caddy_2.8.4_linux_amd64.tar.gz"
          tar -xzf caddy_2.8.4_linux_amd64.tar.gz
          sudo mv caddy /usr/local/bin/
          sudo chmod +x /usr/local/bin/caddy

      - name: Run Caddy
        run: caddy run --config ./Caddyfile
