name: Run Caddy

on:
  push:
    branches:
      - main  # Changez ceci pour la branche de votre choix

jobs:
  run-caddy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # Changez ceci selon la version de Go requise par Caddy

      - name: Install Caddy
        run: |
          go install github.com/caddyserver/caddy/v2@latest
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Run Caddy
        run: caddy run --config ./Caddyfile
