name: Run Caddy

on:
  push:
    branches:
      - main  # Changez ceci pour la branche de votre choix

jobs:
  run-caddy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download rtmp
        run: |
          pip install ffmpeg 
          sudo apt-get install ffmpeg 
          npm i puppeteer
          
      - name: Run rtmp
        run: node rtmp.js
