name: Java Servlet CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Download Servlet API
        run: |
          wget https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar -P /tmp

      - name: Compile Java Servlet
        run: javac -cp /tmp/javax.servlet-api-3.1.0.jar StreamRedirectServlet.java

      - name: Package into WAR file
        run: jar -cvf app.war StreamRedirectServlet.class

      - name: Deploy WAR to Tomcat
        run: |
          sudo cp app.war /path/to/tomcat/webapps/
          sudo systemctl restart tomcat

      - name: Check Tomcat logs
        run: sudo journalctl -u tomcat
        
